### ISSUE TITLE
Getting feedback on the v1.1 prototype card

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/oresat-proto-card#2]
Rough draft of the v2 card is done! We're now awaiting feedback that we're not complete idiots on the v1.1. We need to know:

1. Does it power up?
1. Can you program the STM?
1. Can you blink the LED?
1. Can you talk over UART?
1. Can you talk over CAN?

At that point, we can fire on v2!

**Comment by heliochronix** [comment]
Feedback so far:
CAN_EN (PA10) and CAN_LSTN (PA9) are mislabeled, similar to the Solar V1 issue. They are connected to SHDN (Shutdown mode) and S (Silent mode) on the TCAN330.  Maybe rename CAN_SHDN and CAN_SILENT?

1. Powers up: Check
2. Programmable: Check
3. LED Blinks: Working on it. Some kinda hitch right now.
4. UART: Need to test
5. CAN: Need to test

**Comment by andrewgreenberg** [comment]
Fixed in future OreSat Proto Card and on solar v2 boards. Now called CAN_SHDN and CAN_SILENT, as suggested. Go Miles go!

**Comment by heliochronix** [comment]
1. Does it power up? Yes!
2. Can you program the STM? Yes!
3. Can you blink the LED? Yes!
4. Can you talk over UART? Yes!
5. Can you talk over CAN? Yes!
